import Head from "next/head";
import Header from "../componets/Header";
import Footer from "../componets/Footer";

const Layout = (props) => {
  return (
    <div>
      <Head>
        <title>Next App By Raqib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="content-wrapper">{props.children}</div>

      <Footer />
    </div>
  );
};

export default Layout;
